services:

  fastapi:

    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile

    container_name: fastapi

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    restart: always

    depends_on:
      - rabbitmq

  rabbitmq:

    image: rabbitmq:3.13-management

    container_name: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: always

  worker:

    build:
      context: .
      dockerfile: docker/fastapi/Dockerfile

    container_name: worker

    volumes:
      - .:/app

    depends_on:
      - rabbitmq

    command: python app/worker.py

    restart: always